# CKP8366 - TÓPICOS AVANÇADOS - APRENDIZAGEM DE MÁQUINA PROBABILÍSTICA

<img  src="https://img.shields.io/badge/UFC_CKP8366-VAUX GOMES-000000?style=for-the-badge&logo=" /> <img src="https://img.shields.io/badge/Jupyter-000000?style=for-the-badge&logo=jupyter&logoColor=white" /> <img src="https://img.shields.io/badge/Python-000000?style=for-the-badge&logo=python&logoColor=white" />


In [39]:
#
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


## Gaussian Process

In [ ]:
class GaussianProcess:
  def __init__(self, kernel):
    pass
  
  def __str__(self):
    return f'GaussianProcessRBF'

## Radial Basis Function Kernel

$$k(x_1, x_2) = \exp\left(-\frac{\|x_1 - x_2\|^2}{2\sigma^2}\right)$$

> O slide mostra uma versão ponderada (um pouco diferente)

> $$\displaystyle k(x_i, x_j) = \sigma^2 \exp \left(-\frac{1}{2} \sum_{d=1}^D w_d^2(x_{id} - x_{jd})^2\right)$$

In [55]:
# RBF
def rbf(xi, xj, sigma, weights=None):
  if weights is None:
    weights = np.ones(xi.shape[1]) # No caso vai ser apenas 1 dim
  
  #  
  weights2  = weights**2
  sigma2 = sigma**2
  
  #
  K = np.zeros((xi.shape[0], xj.shape[0])) # Output matrix
  
  #
  for i in range(xi.shape[0]):
    for j in range(xj.shape[0]):
      sum_ = 0
      
      # main loop
      for d in range(xi.shape[1]):
        sum_ += weights2 * (xi[i, d] - xj[j, d])**2
        
      K[i, j] = sigma2 * np.exp(- 0.5 * sum_)
   
        
    return K
  
rbf(X, X, sigma=1)

/var/folders/2_/rvh1zv7d565dmp07jlhl48340000gn/T/ipykernel_7744/4192649456.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  K[i, j] = sigma2 * np.exp(- 0.5 * sum_)


array([[1.        , 0.91594906, 0.89136795, ..., 0.95487084, 0.8974108 ,
        0.93708574],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

#### Carregamento dos dados

In [10]:
# Data
data = np.genfromtxt('./files/gp_data_train.csv', delimiter=',')

# Separation
X = data[:, :-1]
y = data[:, -1:]

# Normalization 
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))           # MinMax 0 ~ 1
y = 2  * (y - y.min(axis=0)) / (y.max(axis=0) - y.min(axis=0)) - 1  # MinMax -1 ~ 1

#
X.shape, y.shape

(np.float64(1.0), np.float64(-1.0), np.float64(1.0))

In [24]:
np.subtract.outer(X[0] , X[1])

array([[0.41903348]])

In [15]:
np.subtract.outer(a, a)

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [26]:
b

array([4, 5])

In [27]:
np.subtract.outer(b, b)

array([[ 0, -1],
       [ 1,  0]])

array([-0.73060254,  0.47775726,  0.93771024,  0.51140807, -0.85667732,
       -1.07213306, -0.6432009 ,  0.75399618,  0.46886824,  0.97991486])

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [44]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((75, 1), (25, 1), (75, 1), (25, 1))

In [45]:
X_train

array([[0.73717792],
       [0.62071648],
       [0.13786173],
       [0.38396351],
       [0.62408241],
       [0.72804247],
       [0.98999346],
       [0.84305158],
       [0.28347277],
       [0.76225112],
       [0.41560977],
       [0.76341022],
       [0.06848833],
       [0.30241336],
       [0.16989129],
       [0.60942349],
       [0.41839138],
       [0.68288454],
       [0.68990236],
       [0.21663366],
       [0.52663701],
       [0.69017656],
       [0.31333796],
       [0.62168719],
       [0.04447241],
       [0.72129602],
       [0.54653754],
       [0.16270199],
       [0.94771555],
       [0.47466176],
       [0.13984601],
       [0.98509615],
       [0.84373829],
       [0.41892344],
       [0.39016039],
       [0.40939647],
       [0.33426983],
       [0.33356297],
       [0.40715389],
       [0.10671603],
       [0.23236353],
       [0.47680872],
       [0.18187135],
       [0.5818937 ],
       [0.39086565],
       [0.69381129],
       [0.10159948],
       [0.877

In [47]:
X.shape

(100, 1)